// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgGcWUQrPG5FH3uiOmRvFMtr3AIgh7Mis',
    appId: '1:733726200712:web:a37e3c7f4b82c6d638e03d',
    messagingSenderId: '733726200712',
    projectId: 'hopin-146af',
    authDomain: 'hopin-146af.firebaseapp.com',
    databaseURL: 'https://hopin-146af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopin-146af.firebasestorage.app',
    measurementId: 'G-Z26HZKW1P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7uKVgcT5xpn8EOKhtexEY5cZSOKguzJM',
    appId: '1:733726200712:android:200bf66e15762dfd38e03d',
    messagingSenderId: '733726200712',
    projectId: 'hopin-146af',
    databaseURL: 'https://hopin-146af-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hopin-146af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjxNxWT1X8IeER9ilUMKp5kcNAzKqGQbA',
    appId: '1:733726200712:ios:42f5e849919ed57f38e03d',
    messagingSenderId: '733726200712',
    projectId: 'hopin-146af',
    storageBucket: 'hopin-146af.firebasestorage.app',
    iosBundleId: 'com.example.hopin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgGcWUQrPG5FH3uiOmRvFMtr3AIgh7Mis',
    appId: '1:733726200712:web:37a779aca9ab2b8a38e03d',
    messagingSenderId: '733726200712',
    projectId: 'hopin-146af',
    authDomain: 'hopin-146af.firebaseapp.com',
    storageBucket: 'hopin-146af.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjxNxWT1X8IeER9ilUMKp5kcNAzKqGQbA',
    appId: '1:733726200712:ios:42f5e849919ed57f38e03d',
    messagingSenderId: '733726200712',
    projectId: 'hopin-146af',
    storageBucket: 'hopin-146af.firebasestorage.app',
    iosBundleId: 'com.example.hopin',
  );

}